export const ErrorCodes = {
  FORBIDDEN_OWNERSHIP: 'FORBIDDEN_OWNERSHIP',
  RBAC_DENIED: 'RBAC_DENIED',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',
  STATUS_REGRESSION: 'STATUS_REGRESSION',
} as const;
