services:
  db:
    image: postgres
    container_name: dbMolla
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: molla_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - dbMolla:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d molla_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lojaonline
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: mollabackend
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/molla_db
      - JWT_PRIVATE_KEY=LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ3lqUVlNcGhROVppek0Kei9rUUtyalMvY3RRTFNhbnRISCtNSWZ4MG5YSnpCcVp5RVk4ZkJjZnMwT2I1N29rSlErU1FXTGdMaXFyTmY5VwpZTmJQMnpmUWdPYWlNc05aUlRDd3crVFhZTXpqOGVobVRhdFFBaFdONW9DUjcyenNXdTFERkFSQzQxM0JIT05RCjVpQWVMeFlZRU42dVdqd3ZYMlVIQnlpRVNlSzgrWlBycUU3ZHhkWXhBMnd1Sm1Pc0JmYzNFQUE4cUpaVnlIYmIKZ201dmxrRGh2UFg1NnFLMEVLaGtsanBML3pLSzBnUlU4djNQbC8zSkxEdFo4eStibGhJbVBwNmUxajJNbVpzQgpaM0wvWkZsYTlpNDVhczN6UVRMVTdOUkliNjRsRFN0ZUVIQW1LOENtRHUrWEV0RFBIU2hUOXpHTTc0TElBa1FWCkx5ZzJXSWM3QWdNQkFBRUNnZ0VBUVJiZDFMQ2Fna09FSTJuUmZzNUVNRTVxMXFDUERlWGZCRzRHc09ZcklGUnkKZ2dzYlo2TkkvcnBuOUNiR21iU1U5NWswaFVydkxSanpLemNFT0NQUE5nZzNpM3Q3OFVnaTF0Mml4ODAzQkFYRQoxYjZNckE4R2NvTkw3V2RkeXMvZTNHd29uWVdyUU9IYUVEekVDcHpacmc1QVQwai8xYmt0NkNENDZUalNHbGMzCitoM3pjWG5Gd0YxWHZQM3dTYTY4M0twSUxBaG9Uc1BzTm9qYmdveEJqb1UwY3A5UWM2cjZhQzhzZXZLNmZVYVgKMzlxYkh3c3FDSUk3QS9hcGJnMkx2RTZjRldXNDExQVc3SlgrcDMxcnBHanBnZ0k4aXFOMG1CS2ZIMGpBV1poQwprc21xVGptZTlwUHhPa0lnV29RSG9OdXB2Sytoelo4ODZVcS84a1dkb1FLQmdRQzZleE9NUmgrMmhDTWR2OU1oCnhpb041ZmpaVmtSUFE2alV4ZVVKVmxYMytELyszbERFRU5ZZEpoYnVFeVAzRVc1NjhyQjQ1bGt0L1Rna2huSXIKcjc2d2tnY3VMKzNocTJ3MCthSUg5VnhyQkZMaTVrOWY0R1FUUkxFUW0vbTl4NHdiUFVlSXp0d0MyaDdpWDREUQpmM1o1UTUyR3VpRUtKTUordURDUFlWWVBLd0tCZ1FEMUhTYjhlNVZKbWxrdlY1bjV3Vy8xbE4wRjVMUUVlU0NwCmU5d1p2bnZxSGF5alc4OVQ0bzA3dkJCakRoOFR2ZDZmUDhCV3dOTDJDRkloeSs2QzFqSlZ6ZXoycElkOVlCY3AKWlZFZlBwUUMyWEhZQjB5RmtDTUJsa09OWkF3L0x2dDczc2FaVUMwRmpobThnYzFtaEk4dS90UGJ5ZTRtdDF5QQo5aXgvdWM3Z01RS0JnQ1Zya3lXZjRMZEFWc2VlZWFDYVlrLzlxT3o3NmFNNlFZUEkza2Y4WWkzclMvUTU2bDBkCnY4bURuakJSK1BLWU5lSklGdTk3MGNOdnY3ZGNuMFp5OHNIOTI2RUNEeXNzdWY3N1pPOVI1aVMzYm1hSHJyL2YKaUZWeGdGS0Q2aDZTRDJSYjdLSGdXTGZkeXpyRHpWYUpiVjJ5R3NjeFRIWDdvR2ZMVUR0RlhmNlhBb0dBYXdQWQpVcUdPTXoxZE5NczFZWkt2MC9PemIvQkRIRFRhS3NUMStwTnN2SEZLUDJSRko2V2c3ZlNVM3ZwNlhQOG5wRFdNClB4UWV4dVlwSGJKUXB2VG5zd2llTGF6MXJxcDJVazkyMUlKWTBzbW01NStBTEV3YXpJV1RacmJJbGdsb0tOUEIKdDR3R3JBYzNlMUxjbjZhK2NORTNKQjJNaVlEQ3RWZEZaRnAyVlBFQ2dZQldBb2V3N29BamNqQnVETm1yc0IySQpBY21IY09CREl1SVRIV1AySjE3VjdVSFA3U3ZsQ21sZElKMGNIUkJTTHhUZDl3Zzl4ZDBBVldmRmJ3ZXpKMmUyCkpQS3JxVnVzeHIrWUdzVGREekh3dkE4bllHN3hFNkpuZGhJYUhac1FBRWk0R0NQdTRFWmM5K0FHTytnSmtDWmEKRkVQdXFXdEJiNkpDZmpNditSWXlaQT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
      - JWT_PUBLIC_KEY=LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeTBqRTIyVjVFWnk5aC9Za0FOMFMNCjdlZUJxYmRDcVF5VzFUWDhUOE9TTFBxT095WUhESEM5czQ5NHA5cjhZd29Td0Fsc2dqSXN1c1Btbm05aTFSYzkNCnp1ekpHOGozV25oeWxNTUxRRGY5Y2VoUFlJSGFjUloxM0ZUVEFqMDNiWFRoOUpHcitLSGFtNHdxL0oxdWpNR3ENCk9ZTkdaV2tBdWVpaTBpMVpBNTJIcXZzaUY4Zzl1SlN3QW16eW1aSlJCWFFweGg5YjVGcXY5d3p5a3craFlhdFYNCmVwT0RkT0RRL3dvSDBhWk1WTFZVcXYvc1RtSU56L25mbG0vV2g1d0tBZDhia2t4MDBtWVBHM2RINm93VTVxQ0YNCkJqMXBXZ0VTYnlEcG9rTUpsakpuWXJFUzQ5RWJtUUdWWUpNb0RHN2I2cVRaU3B6QjI5R281djlTU21CeTNzaFoNCmVRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==
      - PORT=4001
      - EMAIL_FROM=guilherme.padovani93@gmail.com
      - EMAIL_PASS='brle yvba scsv jsne'
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "4001:4001"
    networks:
      - lojaonline
volumes:
  dbMolla:
networks:
  lojaonline:
    driver: bridge
