# etapa 1 - instalacao de dependencias
FROM node:24-alpine AS dependences
WORKDIR /app
COPY ./package.json ./
RUN npm install --force

# etapa 2 - construcao do build
FROM node:24-alpine AS build
WORKDIR /app
COPY --from=dependences /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate
RUN npm run build

# etapa 3 - deploy
FROM node:24-alpine AS deploy
WORKDIR /app
ENV NODE_ENV production

# Execucao
FROM node:24-alpine AS server
WORKDIR /app
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/.env ./.env

COPY --from=build /app/prisma ./prisma
CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
EXPOSE 4001