services:
  db:
    image: postgres
    container_name: dbMolla
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: molla_db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - dbMolla:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d molla_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lojaonline
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: mollabackend
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/molla_db
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "4001:4001"
    networks:
      - lojaonline
volumes:
  dbMolla:
networks:
  lojaonline:
    driver: bridge
