-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'VENDEDOR');

-- CreateEnum
CREATE TYPE "PedidoStatus" AS ENUM ('CRIADO', 'EM_PROCESSAMENTO', 'ENVIADO', 'ENTREGUE');

-- CreateEnum
CREATE TYPE "PagamentoStatus" AS ENUM ('PENDENTE', 'APROVADO', 'RECUSADO');

-- CreateTable
CREATE TABLE "User" (
    "ID_USUARIO" TEXT NOT NULL,
    "S_NOME" TEXT NOT NULL,
    "S_EMAIL" TEXT NOT NULL,
    "S_HASH_SENHA" TEXT NOT NULL,
    "E_ROLE" "Role" NOT NULL,
    "S_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "D_CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "D_UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "Produto" (
    "ID_PRODUTO" TEXT NOT NULL,
    "S_NOME" TEXT NOT NULL,
    "S_DESCRICAO" TEXT,
    "N_PRECOBASE" DECIMAL(10,2) NOT NULL,
    "N_DESCONTO" INTEGER NOT NULL DEFAULT 0,
    "N_ESTOQUE" INTEGER NOT NULL DEFAULT 0,
    "S_ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "D_CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "D_UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Produto_pkey" PRIMARY KEY ("ID_PRODUTO")
);

-- CreateTable
CREATE TABLE "Cliente" (
    "ID_CLIENTE" TEXT NOT NULL,
    "S_NOME" TEXT NOT NULL,
    "S_EMAIL" TEXT NOT NULL,
    "S_DOCUMENTO" TEXT NOT NULL,
    "S_TELEFONE" TEXT,
    "D_CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "D_UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Cliente_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "Endereco" (
    "ID_ENDERECO" TEXT NOT NULL,
    "S_RUA" TEXT NOT NULL,
    "S_NUMERO" TEXT NOT NULL,
    "S_COMPLEMENTO" TEXT,
    "S_BAIRRO" TEXT NOT NULL,
    "S_CIDADE" TEXT NOT NULL,
    "S_UF" TEXT NOT NULL,
    "S_CEP" TEXT NOT NULL,
    "ID_CLIENTE" TEXT NOT NULL,

    CONSTRAINT "Endereco_pkey" PRIMARY KEY ("ID_ENDERECO")
);

-- CreateTable
CREATE TABLE "Pedido" (
    "ID_PEDIDO" TEXT NOT NULL,
    "ID_CLIENTE" TEXT NOT NULL,
    "ID_USUARIO" TEXT NOT NULL,
    "S_STATUS" "PedidoStatus" NOT NULL DEFAULT 'CRIADO',
    "N_TOTALBRUTO" DECIMAL(10,2) NOT NULL,
    "N_TOTALDESCONTO" DECIMAL(10,2) NOT NULL,
    "N_TOTAL_LIQUIDO" DECIMAL(10,2) NOT NULL,
    "D_CREATEDAT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "D_UPDATEDAT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Pedido_pkey" PRIMARY KEY ("ID_PEDIDO")
);

-- CreateTable
CREATE TABLE "PedidoItem" (
    "ID_PEDIDO_ITEM" TEXT NOT NULL,
    "S_NOME_SNAPSHOT" TEXT NOT NULL,
    "N_PREOCO_UNITARIO_SNAPSHOT" DECIMAL(10,2) NOT NULL,
    "N_QUANTIDADE" INTEGER NOT NULL,
    "N_SUBTOTAL" DECIMAL(10,2) NOT NULL,
    "ID_PEDIDO" TEXT NOT NULL,
    "ID_PRODUTO" TEXT NOT NULL,

    CONSTRAINT "PedidoItem_pkey" PRIMARY KEY ("ID_PEDIDO_ITEM")
);

-- CreateTable
CREATE TABLE "Pagamento" (
    "ID_PAGAMENTO" TEXT NOT NULL,
    "S_METODO" TEXT NOT NULL,
    "S_STATUS" "PagamentoStatus" NOT NULL DEFAULT 'PENDENTE',
    "ID_TRANSACAO" TEXT,
    "ID_PEDIDO" TEXT NOT NULL,

    CONSTRAINT "Pagamento_pkey" PRIMARY KEY ("ID_PAGAMENTO")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_S_EMAIL_key" ON "User"("S_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "Endereco_ID_CLIENTE_key" ON "Endereco"("ID_CLIENTE");

-- CreateIndex
CREATE UNIQUE INDEX "Pagamento_ID_PEDIDO_key" ON "Pagamento"("ID_PEDIDO");

-- AddForeignKey
ALTER TABLE "Endereco" ADD CONSTRAINT "Endereco_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "Cliente"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Pedido" ADD CONSTRAINT "Pedido_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "Cliente"("ID_CLIENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Pedido" ADD CONSTRAINT "Pedido_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "User"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PedidoItem" ADD CONSTRAINT "PedidoItem_ID_PEDIDO_fkey" FOREIGN KEY ("ID_PEDIDO") REFERENCES "Pedido"("ID_PEDIDO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PedidoItem" ADD CONSTRAINT "PedidoItem_ID_PRODUTO_fkey" FOREIGN KEY ("ID_PRODUTO") REFERENCES "Produto"("ID_PRODUTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Pagamento" ADD CONSTRAINT "Pagamento_ID_PEDIDO_fkey" FOREIGN KEY ("ID_PEDIDO") REFERENCES "Pedido"("ID_PEDIDO") ON DELETE RESTRICT ON UPDATE CASCADE;
